### ISSUE TITLE
I386 binaries doesn't works

### ISSUE THREAD

**Issue by samiavasil** [kasymovga/qrexuizlauncher#2]
Can't run on 32 bits platform.
It seems like i386 executable is for 64 not for 32 platform for example:

 _objdump -t ./RexuizLauncher.Linux-i386.AppImage 
./RexuizLauncher.Linux-i386.AppImage:     file format elf64-x86-64_

**Comment by kasymovga** [comment]
You right, will fix it soon.

**Comment by kasymovga** [comment]
I re-uploaded corrected (i hope) binaries, please check if problem fixed.

**Comment by kasymovga** [comment]
i think there is also trouble with fonts, will fix it soon.

**Comment by kasymovga** [comment]
Done.
